sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t padmavathi12/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true  padmavathi12/docker-react npm run test -- --coverage
http://dockerreact-env-1.eba-9hyzis72.us-east-2.elasticbeanstalk.com/
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-612338159768"
  bucket_path: "docker-react"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY            
  secret_access_key: $AWS_SECRET_KEY                                                                                                                                                                                                                                                                                                         
